### PR TITLE
Hello World

### PR DESCRIPTION
**Pull request by Krishnabot**
In this feature I added a header with the text Hello World and styled it with my favorite color!

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -0,0 +1,2 @@
+node_modules/
+test.md
```
Comment (vechicin) [inline .gitignore:2]: While the `test.md` file was correctly added to the `.gitignore` file, the `node_modules` directory was not. Kindly fix this as it is a project requirement.

You may want to research the following Git command: `git rm -r --cached`.

File: .stickler.yml [hunk 2]
```diff
@@ -0,0 +1,10 @@
+# add the linters you want stickler to use for this project
+linters:
+  stylelint:
+    # indicate where is the config file for stylelint
+    config: "stylelint.config.js"
+    
+# PLEASE DO NOT enable auto fixing options
+# if you need extra support from you linter - do it in your local env as described in README for this config
+
+# find full documentation here: https://stickler-ci.com/docs
```
Comment (vechicin) [inline .stickler.yml]: Kindly remove this linter, you need to use Microverse's linters without any additional ones.

File: README.md [hunk 3]
```diff
@@ -2,71 +2,32 @@
 
 # Project Name
 
-> Description the project.
+> Hello microverse
```
Comment (vechicin) [inline README.md]: There are a couple of tweaks in the README that I suggest you implement. In the `Project Name` header you need to type the project's name and in the `Description` section you need to type a description for the project.

File: README.md [hunk 4]
```diff
@@ -2,71 +2,32 @@
...
-
-### Setup
-
-### Install
-
-### Usage
-
-### Run tests
-
-### Deployment
```
Comment (vechicin) [inline README.md:37]: I suggest you add the instructions on how to get a local copy of the project and how to install the required dependencies for it to run properly.

**Review by vechicin — CHANGES_REQUESTED** [review]
# Hi @Krishnabot  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good commit history
- [x] Correct GitHub Flow use

## Required Changes ♻️

- [ ] I suggest you change your PR title and add a description to it as they are part of the [project requirements](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md).
Here is what I suggest:
Title: Hello World
Description: In this feature I added a header with the text `Hello World` and styled it with my favorite color!
- [ ] Be very careful about pushing the `node_modules` directory. Due to the number of files in that directory, it may overload GitHub and make the reviewing process a nightmare for us code reviewers.
- [ ] I suggest you use Microverse's linters **exclusively,** you can find a step-by-step guide on how to install them [here](https://github.com/microverseinc/linters-config/blob/master/html-css/README.md). Please remove Stickler and the `lighthouseci` folder.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vechicin** [comment]
https://github.com/Krishnabot/Hello-Microverse/blob/0d67aa352201dd5cbf4cb284d8c80fdeb4ccbe9a/style.css#L1-L11
[OPTIONAL] Using color names is considered bad practice. I suggest you change these colors to their `rgb` or `hex` equivalents.

File: .gitignore (hunk 1 above)
Comment (Krishnabot) [reply .gitignore:2]: Hi, Thank you for your suggestion for web hint I am getting following  weird error , please help ! though I have run 
npm install --save-dev hint@6.x
`Error: Cannot find module '@hint/utils-dom'
Require stack:`

and for stylelint I can run successfully in my local machine but it is showing some errors in github . please help

Comment (vechicin) [reply .gitignore:2]: When installing Webhint and/or Stylelint or any other linter make sure you copy the `.github/workflows` directories into the project's root directory. After that execute the npm commands (I recommend you copy and paste them directly into your terminal from the README) and then copy the `hintrc` and `stylelintrc.json` files into the root directory as well. I hope this was useful.

Comment (Krishnabot) [reply .gitignore:2]: I have copied  `.github/workflows` into project root directory . I have executed all the npm commands as recommended . still it is showing errors , can you suggest any else method.

Comment (Krishnabot) [reply .gitignore:2]: in both stylelint and web lint i am getting following error 
` This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!`

File: .stickler.yml (hunk 2 above)
Comment (Krishnabot) [reply .stickler.yml]: Hi, can you review IT again? the issue has been resolved.

File: README.md [hunk 5]
```diff
@@ -2,71 +2,32 @@
 
 # Project Name
 
-> Description the project.
+> Hello microverse
```
Comment (leonardodiasb) [inline README.md]: - [ ] Please add the Project Name as the title of the document and the description below it. You could change `# Project Name` to `# Hello Microverse` and add a description below it.

File: .stickler.yml (hunk 2 above)
Comment (vechicin) [reply .stickler.yml]: @Krishnabot Hi, you need to submit another request through your dashboard, please.

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
...
You used proper GitHub Flow ✔️
Your linter checks are passing ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.
- [ ] Please make sure you add the description of the PR in the first comment. You can click on the `...` at the top right corner of the comment and click on edit and then add a descriptive description of the PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

File: .stickler.yml (hunk 2 above)
Comment (Krishnabot) [reply .stickler.yml]: Ok I have already submitted another request through my dash board .  but Do I need to create another pull request ? I have submitted the same pull request

**Review by topeogunleye — APPROVED** [review]
### Hi @Krishnabot, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
> 
> ## [Optional] suggestions:
> * [ ]  Please kindly ensure all linters are passing.
Screenshot from 2022-05-25 17-39-20
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
